	function change(){
		var textarea = document.getElementById('textarea1');
		textarea.scrollTop = textarea.scrollHeight;
	}
	
	function fun(value){
		 keyboard.display.value+=value;
	}
	


	var c = 0;
	var f = 0;
	var a = 0;
	
	function shiftkey(){
			c=c+1;
			a=a+1;
			if(c<2){
				document.getElementById('1').value="Â±"
				document.getElementById('2').value="U"
				document.getElementById('3').value="Ã‹"
				document.getElementById('4').value="ÃŒ"
				document.getElementById('5').value="Ã†"
				document.getElementById('6').value="Ã«"
				document.getElementById('7').value="Ã¬"
				document.getElementById('8').value="Ã­"
				document.getElementById('9').value="Ã¯"
				document.getElementById('0').value="Ã®"
				document.getElementById('h').value="Ã"
				document.getElementById('n').value="I"
				document.getElementById('c').value="Â½"
				document.getElementById('r').value="Ã»"
				document.getElementById('k').value="Å¾"
				document.getElementById('d').value="Â¡"
				document.getElementById('t').value="Â»"
				document.getElementById('s').value="s"
				document.getElementById('w').value="w"
				document.getElementById('l').value="l"
				document.getElementById('m').value="m"
				document.getElementById('g').value="g"
				document.getElementById('b').value="b"
				document.getElementById('ng').value="\\"
				document.getElementById('p').value="p"
				document.getElementById('j').value="j"
				document.getElementById('y').value="y"
				document.getElementById('z').value="z"
				document.getElementById('q').value="q"
				document.getElementById('[').value="["
				document.getElementById(']').value="]"
				document.getElementById('a').value="a"
				document.getElementById('f').value="f"
				document.getElementById('x').value="x"
				document.getElementById('v').value="v"
				document.getElementById('`').value="`"
				document.getElementById('Ã').value="Ã"
				document.getElementById('.').value="."
				document.getElementById(',').value=","
				document.getElementById('ai').value="Ã¼"
				document.getElementById('cha').value="Ãˆ"
				document.getElementById('/').value="/"
				document.getElementById(';').value=":"
			}else{
				document.getElementById('1').value="1"
				document.getElementById('2').value="2"
				document.getElementById('3').value="3"
				document.getElementById('4').value="4"
				document.getElementById('5').value="5"
				document.getElementById('6').value="6"
				document.getElementById('7').value="7"
				document.getElementById('8').value="8"
				document.getElementById('9').value="9"
				document.getElementById('0').value="0"
				document.getElementById('h').value="h"
				document.getElementById('n').value="n"
				document.getElementById('c').value="c"
				document.getElementById('r').value="r"
				document.getElementById('k').value="k"
				document.getElementById('d').value="d"
				document.getElementById('t').value="t"
				document.getElementById('s').value="s"
				document.getElementById('w').value="w"
				document.getElementById('l').value="l"
				document.getElementById('m').value="m"
				document.getElementById('g').value="g"
				document.getElementById('b').value="b"
				document.getElementById('ng').value="\\"
				document.getElementById('p').value="p"
				document.getElementById('j').value="j"
				document.getElementById('y').value="y"
				document.getElementById('z').value="z"
				document.getElementById('q').value="q"
				document.getElementById('[').value="["
				document.getElementById(']').value="]"
				document.getElementById('a').value="a"
				document.getElementById('f').value="f"
				document.getElementById('x').value="x"
				document.getElementById('v').value="v"
				document.getElementById('`').value="`"
				document.getElementById('Ã').value="Ã"
				document.getElementById('.').value="."
				document.getElementById(',').value=","
				document.getElementById('ai').value="Ã¼"
				document.getElementById('cha').value="Ãˆ"
				document.getElementById('/').value="/"
				document.getElementById(';').value=";"
				c=0;
			};}
			

			

			

	
	function small(){
			if(a>0){
				document.getElementById('1').value="1"
				document.getElementById('2').value="2"
				document.getElementById('3').value="3"
				document.getElementById('4').value="4"
				document.getElementById('5').value="5"
				document.getElementById('6').value="6"
				document.getElementById('7').value="7"
				document.getElementById('8').value="8"
				document.getElementById('9').value="9"
				document.getElementById('0').value="0"
				document.getElementById('h').value="h"
				document.getElementById('n').value="n"
				document.getElementById('c').value="c"
				document.getElementById('r').value="r"
				document.getElementById('k').value="k"
				document.getElementById('d').value="d"
				document.getElementById('t').value="t"
				document.getElementById('s').value="s"
				document.getElementById('w').value="w"
				document.getElementById('l').value="l"
				document.getElementById('m').value="m"
				document.getElementById('g').value="g"
				document.getElementById('b').value="b"
				document.getElementById('ng').value="\\"
				document.getElementById('p').value="p"
				document.getElementById('j').value="j"
				document.getElementById('y').value="y"
				document.getElementById('z').value="z"
				document.getElementById('q').value="q"
				document.getElementById('[').value="["
				document.getElementById(']').value="]"
				document.getElementById('a').value="a"
				document.getElementById('f').value="f"
				document.getElementById('x').value="x"
				document.getElementById('v').value="v"
				document.getElementById('`').value="`"
				document.getElementById('Ã').value="Ã"
				document.getElementById('.').value="."
				document.getElementById(',').value=","
				document.getElementById('ai').value="Ã¼"
				document.getElementById('cha').value="Ãˆ"
				document.getElementById('/').value="/"
				document.getElementById(';').value=";"
				
				a=0;
			};

	}
	function caps(){
			f= f+1;
			if (f<2){
				
				document.getElementById('1').value="!"
				document.getElementById('2').value="@"
				document.getElementById('3').value="#"
				document.getElementById('4').value="$"
				document.getElementById('5').value="%"
				document.getElementById('6').value="^"
				document.getElementById('7').value="&"
				document.getElementById('8').value="Ã¨"
				document.getElementById('9').value="("
				document.getElementById('0').value=")"
				document.getElementById('h').value="Ã€"
				document.getElementById('n').value="Ã‚"
				document.getElementById('c').value="Ã‡"
				document.getElementById('r').value="Ã‰"
				document.getElementById('k').value="Ã"
				document.getElementById('d').value="Ã‘"
				document.getElementById('t').value="Ã“"
				document.getElementById('s').value="uÃ¦"
				document.getElementById('w').value="Ã™"
				document.getElementById('l').value="Ãž"
				document.getElementById('m').value="ÃŸ"
				document.getElementById('g').value="Ã¡"
				document.getElementById('b').value="Ã£"
				document.getElementById('ng').value="Ã¥"
				document.getElementById('p').value="Ã¦"
				document.getElementById('j').value="Ã©"
				document.getElementById('y').value="Ãª"
				document.getElementById('z').value="Ã±"
				document.getElementById('q').value="Ã”"
				document.getElementById('[').value="Ã—"
				document.getElementById(']').value="Ã–"
				document.getElementById('a').value="Ã’"
				document.getElementById('f').value="Ã¢"
				document.getElementById('x').value="Ã…"
				document.getElementById('v').value="Ã¤"
				document.getElementById('`').value="Ã•"
				document.getElementById('Ã').value="ÃŠ"
				document.getElementById('.').value=">"
				document.getElementById(',').value="<"
				document.getElementById('ai').value="Ã°"
				document.getElementById('cha').value="Ãˆ"
				document.getElementById('/').value="/"
				document.getElementById(';').value=";"
				document.getElementById('i').value="Ã·"
				document.getElementById('u').value="Ãº"
				document.getElementById('o').value="Ã½"
				document.getElementById('e').value="E"
				
				
            }else{
            	
				document.getElementById('1').value="1"
				document.getElementById('2').value="2"
				document.getElementById('3').value="3"
				document.getElementById('4').value="4"
				document.getElementById('5').value="5"
				document.getElementById('6').value="6"
				document.getElementById('7').value="7"
				document.getElementById('8').value="8"
				document.getElementById('9').value="9"
				document.getElementById('0').value="0"
				document.getElementById('h').value="h"
				document.getElementById('n').value="n"
				document.getElementById('c').value="c"
				document.getElementById('r').value="r"
				document.getElementById('k').value="k"
				document.getElementById('d').value="d"
				document.getElementById('t').value="t"
				document.getElementById('s').value="s"
				document.getElementById('w').value="w"
				document.getElementById('l').value="l"
				document.getElementById('m').value="m"
				document.getElementById('g').value="g"
				document.getElementById('b').value="b"
				document.getElementById('ng').value="\\"
				document.getElementById('p').value="p"
				document.getElementById('j').value="j"
				document.getElementById('y').value="y"
				document.getElementById('z').value="z"
				document.getElementById('q').value="q"
				document.getElementById('[').value="["
				document.getElementById(']').value="]"
				document.getElementById('a').value="a"
				document.getElementById('f').value="f"
				document.getElementById('x').value="x"
				document.getElementById('v').value="v"
				document.getElementById('`').value="`"
				document.getElementById('Ã').value="Ã"
				document.getElementById('.').value="."
				document.getElementById(',').value=","
				document.getElementById('ai').value="Ã¼"
				document.getElementById('cha').value="Ãˆ"
				document.getElementById('/').value="/"
				document.getElementById(';').value=";"
				document.getElementById('i').value="i"
				document.getElementById('u').value="u"
				document.getElementById('o').value="o"
				document.getElementById('e').value="e"
				f=0
				
            };}
