	function change(){
		var textarea = document.getElementById('textarea1');
		textarea.scrollTop = textarea.scrollHeight;
	}
	
	function fun(value){
		 keyboard.display.value+=value;
	}
	


	var c = 0;
	var f = 0;
	var a = 0;
	
	function shiftkey(){
			c=c+1;
			a=a+1;
			if(c<2){
				document.getElementById('1').value="±"
				document.getElementById('2').value="U"
				document.getElementById('3').value="Ë"
				document.getElementById('4').value="Ì"
				document.getElementById('5').value="Æ"
				document.getElementById('6').value="ë"
				document.getElementById('7').value="ì"
				document.getElementById('8').value="í"
				document.getElementById('9').value="ï"
				document.getElementById('0').value="î"
				document.getElementById('h').value="Á"
				document.getElementById('n').value="I"
				document.getElementById('c').value="½"
				document.getElementById('r').value="û"
				document.getElementById('k').value="ž"
				document.getElementById('d').value="¡"
				document.getElementById('t').value="»"
				document.getElementById('s').value="s"
				document.getElementById('w').value="w"
				document.getElementById('l').value="l"
				document.getElementById('m').value="m"
				document.getElementById('g').value="g"
				document.getElementById('b').value="b"
				document.getElementById('ng').value="\\"
				document.getElementById('p').value="p"
				document.getElementById('j').value="j"
				document.getElementById('y').value="y"
				document.getElementById('z').value="z"
				document.getElementById('q').value="q"
				document.getElementById('[').value="["
				document.getElementById(']').value="]"
				document.getElementById('a').value="a"
				document.getElementById('f').value="f"
				document.getElementById('x').value="x"
				document.getElementById('v').value="v"
				document.getElementById('`').value="`"
				document.getElementById('Ï').value="Ï"
				document.getElementById('.').value="."
				document.getElementById(',').value=","
				document.getElementById('ai').value="ü"
				document.getElementById('cha').value="È"
				document.getElementById('/').value="/"
				document.getElementById(';').value=":"
			}else{
				document.getElementById('1').value="1"
				document.getElementById('2').value="2"
				document.getElementById('3').value="3"
				document.getElementById('4').value="4"
				document.getElementById('5').value="5"
				document.getElementById('6').value="6"
				document.getElementById('7').value="7"
				document.getElementById('8').value="8"
				document.getElementById('9').value="9"
				document.getElementById('0').value="0"
				document.getElementById('h').value="h"
				document.getElementById('n').value="n"
				document.getElementById('c').value="c"
				document.getElementById('r').value="r"
				document.getElementById('k').value="k"
				document.getElementById('d').value="d"
				document.getElementById('t').value="t"
				document.getElementById('s').value="s"
				document.getElementById('w').value="w"
				document.getElementById('l').value="l"
				document.getElementById('m').value="m"
				document.getElementById('g').value="g"
				document.getElementById('b').value="b"
				document.getElementById('ng').value="\\"
				document.getElementById('p').value="p"
				document.getElementById('j').value="j"
				document.getElementById('y').value="y"
				document.getElementById('z').value="z"
				document.getElementById('q').value="q"
				document.getElementById('[').value="["
				document.getElementById(']').value="]"
				document.getElementById('a').value="a"
				document.getElementById('f').value="f"
				document.getElementById('x').value="x"
				document.getElementById('v').value="v"
				document.getElementById('`').value="`"
				document.getElementById('Ï').value="Ï"
				document.getElementById('.').value="."
				document.getElementById(',').value=","
				document.getElementById('ai').value="ü"
				document.getElementById('cha').value="È"
				document.getElementById('/').value="/"
				document.getElementById(';').value=";"
				c=0;
			};}
			

			

			

	
	function small(){
			if(a>0){
				document.getElementById('1').value="1"
				document.getElementById('2').value="2"
				document.getElementById('3').value="3"
				document.getElementById('4').value="4"
				document.getElementById('5').value="5"
				document.getElementById('6').value="6"
				document.getElementById('7').value="7"
				document.getElementById('8').value="8"
				document.getElementById('9').value="9"
				document.getElementById('0').value="0"
				document.getElementById('h').value="h"
				document.getElementById('n').value="n"
				document.getElementById('c').value="c"
				document.getElementById('r').value="r"
				document.getElementById('k').value="k"
				document.getElementById('d').value="d"
				document.getElementById('t').value="t"
				document.getElementById('s').value="s"
				document.getElementById('w').value="w"
				document.getElementById('l').value="l"
				document.getElementById('m').value="m"
				document.getElementById('g').value="g"
				document.getElementById('b').value="b"
				document.getElementById('ng').value="\\"
				document.getElementById('p').value="p"
				document.getElementById('j').value="j"
				document.getElementById('y').value="y"
				document.getElementById('z').value="z"
				document.getElementById('q').value="q"
				document.getElementById('[').value="["
				document.getElementById(']').value="]"
				document.getElementById('a').value="a"
				document.getElementById('f').value="f"
				document.getElementById('x').value="x"
				document.getElementById('v').value="v"
				document.getElementById('`').value="`"
				document.getElementById('Ï').value="Ï"
				document.getElementById('.').value="."
				document.getElementById(',').value=","
				document.getElementById('ai').value="ü"
				document.getElementById('cha').value="È"
				document.getElementById('/').value="/"
				document.getElementById(';').value=";"
				
				a=0;
			};

	}
	function caps(){
			f= f+1;
			if (f<2){
				
				document.getElementById('1').value="!"
				document.getElementById('2').value="@"
				document.getElementById('3').value="#"
				document.getElementById('4').value="$"
				document.getElementById('5').value="%"
				document.getElementById('6').value="^"
				document.getElementById('7').value="&"
				document.getElementById('8').value="è"
				document.getElementById('9').value="("
				document.getElementById('0').value=")"
				document.getElementById('h').value="À"
				document.getElementById('n').value="Â"
				document.getElementById('c').value="Ç"
				document.getElementById('r').value="É"
				document.getElementById('k').value="Ð"
				document.getElementById('d').value="Ñ"
				document.getElementById('t').value="Ó"
				document.getElementById('s').value="uæ"
				document.getElementById('w').value="Ù"
				document.getElementById('l').value="Þ"
				document.getElementById('m').value="ß"
				document.getElementById('g').value="á"
				document.getElementById('b').value="ã"
				document.getElementById('ng').value="å"
				document.getElementById('p').value="æ"
				document.getElementById('j').value="é"
				document.getElementById('y').value="ê"
				document.getElementById('z').value="ñ"
				document.getElementById('q').value="Ô"
				document.getElementById('[').value="×"
				document.getElementById(']').value="Ö"
				document.getElementById('a').value="Ò"
				document.getElementById('f').value="â"
				document.getElementById('x').value="Å"
				document.getElementById('v').value="ä"
				document.getElementById('`').value="Õ"
				document.getElementById('Ï').value="Ê"
				document.getElementById('.').value=">"
				document.getElementById(',').value="<"
				document.getElementById('ai').value="ð"
				document.getElementById('cha').value="È"
				document.getElementById('/').value="/"
				document.getElementById(';').value=";"
				document.getElementById('i').value="÷"
				document.getElementById('u').value="ú"
				document.getElementById('o').value="ý"
				document.getElementById('e').value="E"
				
				
            }else{
            	
				document.getElementById('1').value="1"
				document.getElementById('2').value="2"
				document.getElementById('3').value="3"
				document.getElementById('4').value="4"
				document.getElementById('5').value="5"
				document.getElementById('6').value="6"
				document.getElementById('7').value="7"
				document.getElementById('8').value="8"
				document.getElementById('9').value="9"
				document.getElementById('0').value="0"
				document.getElementById('h').value="h"
				document.getElementById('n').value="n"
				document.getElementById('c').value="c"
				document.getElementById('r').value="r"
				document.getElementById('k').value="k"
				document.getElementById('d').value="d"
				document.getElementById('t').value="t"
				document.getElementById('s').value="s"
				document.getElementById('w').value="w"
				document.getElementById('l').value="l"
				document.getElementById('m').value="m"
				document.getElementById('g').value="g"
				document.getElementById('b').value="b"
				document.getElementById('ng').value="\\"
				document.getElementById('p').value="p"
				document.getElementById('j').value="j"
				document.getElementById('y').value="y"
				document.getElementById('z').value="z"
				document.getElementById('q').value="q"
				document.getElementById('[').value="["
				document.getElementById(']').value="]"
				document.getElementById('a').value="a"
				document.getElementById('f').value="f"
				document.getElementById('x').value="x"
				document.getElementById('v').value="v"
				document.getElementById('`').value="`"
				document.getElementById('Ï').value="Ï"
				document.getElementById('.').value="."
				document.getElementById(',').value=","
				document.getElementById('ai').value="ü"
				document.getElementById('cha').value="È"
				document.getElementById('/').value="/"
				document.getElementById(';').value=";"
				document.getElementById('i').value="i"
				document.getElementById('u').value="u"
				document.getElementById('o').value="o"
				document.getElementById('e').value="e"
				f=0
				
            };}
